---
title: "Evaluating Claims of Extraterrestrial Messaging"
author: Bilal Haq
thanks: "Code and data are available at: https://github.com/haqbilal/Evaluating-Claims-of-Extraterrestrial-Messaging"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Suppose that in the late twenty-first century, astronomers announce the receipt of a candidate message from extraterrestrial intelligence. They provide information about the message itself and about the candidate planet of origin. In this paper, we assess the authenticity of the candidate message, the likelihood that it comes from the candidate planet, and the possible biochemistry of the senders. We look at p2 and p3 of the given three, corresponding to pdf files p2 and p3. The analysis was conducted using @citeR. The data was obtained from http://astro.utoronto.ca/~ast251/AST251_2022_Project3/"
output: bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Methodology

## Properties of the message

We will focus on planets 2 and 3 of the given datasets, to be referred to as p2 and p3 from here on. Firstly, we want to determine if the transmission came from intelligent life. In this case, we are looking for patterns among the transmission, such as repeating phrases, as evidence of intelligence, whereas a seemingly random transmission would provide evidence against an intelligent sender. After that, we attempt to decode the candidate extraterrestrial messages, in hopes of deriving some meaning or context to them. This would provide further evidence towards the sender being intelligent, as it reduces the likelihood that the non-random pattern was generated purely through nature (i.e. ocean tides, variable stars, dripping water). To decode the message, we follow the procedure by @aricebo. This entails taking two prime factors whose product is the length of the message, and creating a grid whose length and width are those prime numbers. Then, we colour the elements of the grid corresponding to 0s in white, and the elements corresponding to 1s in black. This will create an image that is the proposed message sent by the extraterrestrials. If the image appears to follow a pattern, such as resemblance to a shape, we can further conclude that it was likely made by an intelligent life form, and not randomly generated by nature.

## Properties of the planet

Planets in the habitable zone are capable of hosting life, and so we must calculate each planet's star's habitable zone radius to determine if that planet is a valid candidate. We use the method provided by @habitable_zone, which requires the star's luminosity in solar luminosity units. This will give a radius in astronomical units (AU) which can then be converted into lightyears to determine if the planet is in range. Moving on, we will look towards determining if the planet hosts life, depending on various properties, called biosignatures. In the same way as @biosignatures, we categorize biosignatures into three groups: gaseous, surface, and temporal. Gaseous biosignatures are indicators of the presence of life forms with metabolism. The presence of an Earth-like atmosphere (i.e. containing mostly NO2, CO2, and H2O) provides evidence that the planet hosts life. Surface biosignatures are features of the radiation scattered or reflected by organisms. The absorption and reflection of light may affect the color spectrum on the surface of a planet, which is indicative of processes undergoing such as photosynthesis. Lastly, temporal biosignatures are changes in measurable quantities over time. Seasonal dips and ascents in different gasses over time may indicate chemical cycles taking place in the atmosphere, which bodes well for the planet to be hosting life.

# Analysis

## Planet 1 (p2)

The message received from this planet is a narrowband optical transmission. The length of the message is 131 binary digits long, so there are 131 bits of information. There are 122 zeroes, and 9 ones. There are no factors of 131 except for 1 and itself (it is a prime number), so the Aricebo method of decoding the message does not work. However, we can still look for patterns in the transmission in deciding if it came from intelligent life. Between each 1, there are a different number of 0s, and the number of 0s between each 1 from the left to right is 2, 1, 3, 4, 7, 11, 18, 29, 47. Observe that the number of 0s between a subsequent set of 1s is equal to the sum of that number for the previous two sets of 1s (i.e. 3 = 1 + 2, 4 = 3 + 1, 7 = 4 + 3, etc.). This is a pattern, and so we have a possible sign of intelligent life having sent the transmission. 

Now we use the properties of the planet to infer more about the kind of life on this planet. Firstly, the habitable zone calculation below gives us the radius of p2's habitable zone.

\begin{align*}
d = \sqrt{\frac{L_{\text{star}}}{L_\text{sun}}} = \sqrt{1.22} \approx 1.105 \text{ AU}
\end{align*}

So the habitable zone radius lower bound and upper bound are $0.95d = 1.05$ AU and $1.37d = 1.51$ AU. The planet p2 is 665.5 lightyears away from the star, which is $4.2 \cdot 10^7$ AU. So it is not in the habitable zone, however, we can still assess the other properties to determine if it supports life. That is, looking at the biosignatures as indicators for life existing on the planet, as discussed previously. The planet's atmospheric composition indeed comprises mainly of N2, CO2, O2, and H20, which makes it have an Earth-like atmosphere. Furthermore, looking at the maps of the surface, we have a change in colour from 530 days to 825 days, thus some organic process such as photosynthesis, may be occuring on the planet. As well, the graphs of CO2, O2, and other carbon/oxygen related compounds show evidence of seasonal shifts in the amounts present in the atmosphere. Thus we have 3 biosignatures pointing towards life existing on the planet. Furthermore, due to the Earth-like composition of this planet, it is likely that the biochemistry of life is like the carbon-water chemistry of life on Earth.

## Planet 2 (p3)

The message received from this planet is a narrowband optical transmission. The length of the message is 230 binary digits long, so there are 230 bits of information. There are 10 zeroes, and 220 ones. There are no two prime numbers such that their product equals 230, so the Aricebo method of decoding the message fails. However, we still look for patterns in the message to determine if it originated from intelligent life. Between each set of 0s, there is a different number of 1s, and the number of 1s between each set of 0s, from left to right is 4, 8, 12, 16, 20, 24, 28, 32, 36, 40. These numbers are the first 10 multiples of 4. Since it is unlikely that this pattern was generated naturally, we have evidence that the transmission did come from intelligent life.

Moving on, we can look at the properties of this planet, p3, in the same way as for p2. Beginning with the habitable zone, we calculate it as

\begin{align*}
d = \sqrt{\frac{L_{\text{star}}}{L_\text{sun}}} = \sqrt{0.539} \approx 0.734 \text{ AU}
\end{align*}

To obtain the lower and upper radius bounds, we have $0.95d = 0.70$ AU and $1.37d = 1.01$ AU. Our planet is 60 lightyears away from the star, which is $3.79 \cdot 10^6$ AU. So it appears to not be in the habitable zone, however looking at the other properties will help determine if it has life on it. In terms of gaseous biosignatures, the planet's composition contains N2, CO2, O2, and H20, which makes it similar to Earth. This is evidence that life may exist. Moreover, the differing spectrum of colours observed on the surface maps over time indicate the ongoing of possibly organic procedures, which bodes further evidence. Finally, there do appear to be seasonal shifts in the abundances of CO2 and O2, which are likely caused by the cyclic behavior of life keeping the chemicals out of equilibrium. Overall, we have enough information to conclude that life on this planet probably exists, and has a carbon-water biochemistry similar to that on Earth.

# Discussion

In conclusion, we were able to take the transmitted messages and prove that they showed signs of intelligence, although we were not able to fully decode them. On the other hand, both planets demonstrate evidence that life exists and is ongoing on them, but the habitable zone calculations are a discrepancy. Both planets appear to be very far away from their star, than would be needed. However, in light of all the evidence supporting the existance of life, we can overrule this issue given what we do know.

\newpage

# References

---
nocite: |
  @biochemistry
---


